from django.urls import path
from .views import (
  ClusterFaces,
  CreateRoom,
  DeleteImages,
  DeleteRoom,
  DownloadImagesZip,
  IndexPage,
  JoinRoom,
  RoomImages,
  RoomPage,
  SearchPerson,
  UploadImages,
  UploadZip,
  UserLoginView,
  logout_page,
  signup_page,
)
urlpatterns = [
  path('login/', UserLoginView.as_view(), name='login'),
  path('signup/', signup_page, name='signup'),
  path('logout/', logout_page, name='logout'),
  path('', IndexPage.as_view()),
  path('room/', RoomPage.as_view()),
  path('upload-images/', UploadImages.as_view()),
  path('upload-zip/',UploadZip.as_view()),
  path('create_room/', CreateRoom.as_view()),
  path('join_room/', JoinRoom.as_view()),
  path('room-images/<str:code>/', RoomImages.as_view()),
  path('delete-images/', DeleteImages.as_view()),
  path('delete-room/', DeleteRoom.as_view()),
  path('download-images/', DownloadImagesZip.as_view()),
  path('cluster/',ClusterFaces.as_view()),
  path('search-person/', SearchPerson.as_view()),
]