# Generated by GitHub Copilot on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_room_image_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="embeddings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="face_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
