"""
Django settings for photo_ai project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Optional: load environment variables from .env for local development
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^r#6_h@pv!5kxb1qxdp(4lhm3^$hcmwm$(k8n0b+4#icp9*mur'

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for local development; override with DEBUG=0 on Render.
_debug_env = (os.environ.get("DEBUG") or "").strip().lower()
DEBUG = True if _debug_env == "" else _debug_env in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Render sets RENDER_EXTERNAL_HOSTNAME for web services.
_render_host = (os.environ.get("RENDER_EXTERNAL_HOSTNAME") or "").strip()
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

# Back-compat / explicit host allowlist.
_extra_hosts = (os.environ.get("ALLOWED_HOSTS") or "").strip()
if _extra_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in _extra_hosts.split(",") if h.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'photos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'photo_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'photo_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


def _resolve_ipv4(hostname: str) -> str:
    """Return an IPv4 address for hostname when possible.

    Render environments sometimes fail to reach Supabase over IPv6.
    Forcing an IPv4 address avoids libpq choosing an AAAA record.
    """
    try:
        infos = socket.getaddrinfo(hostname, None, family=socket.AF_INET, type=socket.SOCK_STREAM)
        if infos:
            return infos[0][4][0]
    except Exception:
        pass
    return hostname


def _is_render() -> bool:
    return bool(
        os.environ.get("RENDER")
        or os.environ.get("RENDER_SERVICE_ID")
        or os.environ.get("RENDER_EXTERNAL_HOSTNAME")
    )


def _db_from_url(db_url: str):
    parsed = urlparse(db_url)
    scheme = (parsed.scheme or "").lower()
    if scheme not in {"postgres", "postgresql"}:
        raise ValueError("Only postgres/postgresql URLs are supported")

    qs = parse_qs(parsed.query or "")
    sslmode = (qs.get("sslmode", [None])[0] or "require").lower()

    name = (parsed.path or "").lstrip("/")
    if not name:
        name = "postgres"

    host = parsed.hostname or "localhost"

    # Workaround: Render sometimes can't reach Supabase over IPv6.
    # If we're on Render and the hostname is a Supabase domain, force IPv4.
    if _is_render() and host.endswith(".supabase.co"):
        host = _resolve_ipv4(host)

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": parsed.username or "postgres",
        "PASSWORD": parsed.password or "",
        "HOST": host,
        "PORT": str(parsed.port or 5432),
        "CONN_MAX_AGE": 60,
        "OPTIONS": {
            "sslmode": sslmode,
        },
    }


# Use Supabase Postgres when configured; otherwise keep SQLite.
# Prefer pooler URL when provided (recommended on Render):
# - Transaction pooler URLs commonly use port 6543.
_supabase_db_url = (
    os.environ.get("SUPABASE_POOLER_URL")
    or os.environ.get("SUPABASE_DB_POOLER_URL")
    or os.environ.get("SUPABASE_DB_URL")
    or os.environ.get("DATABASE_URL")
)
if _supabase_db_url:
    DATABASES["default"] = _db_from_url(_supabase_db_url)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Helps local dev (and some platforms) serve app static without requiring collectstatic.
WHITENOISE_USE_FINDERS = True

# In production, prefer hashed + compressed assets (requires collectstatic).
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
